### ISSUE TITLE
Allow API Key to be specified in config or read from file

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot-plugin-chatops-meraki#22]
When deploying this plugin in our environment I store the API key in hashicorp vault.  I can query vault in the Nautobot config file very easily.  I can also use the vault agent to inject the secret as a file but injecting it as an environment variable is much harder with vault and arguably less secure.  I would suggest allowing this variable to be set in the config file where I can configure any way I might want.

**Comment by ubajze** [comment]
Looks like you can pass the API key as a variable.
https://github.com/meraki/dashboard-api-python/blob/371047b7d362a2b7023447c5e261501bb0b29cad/meraki/__init__.py#L78

It would be great if we can read the API key from Nautobot settings instead of rely on the env variable only.
